cd /silent
export HDB_MASSIMPORT=yes
/mnt/sapbits/SWPM10_SP19_Patches/Sapinst SAPINST_PARAMETER_CONTAINER_URL=inifile.xml SAPINST_EXECUTE_PRODUCT_ID=NW_ABAP_OneHost:BS2016.ERP608.HDB.PD SAPINST_SKIP_DIALOGS=true -nogui -noguiserver
